### ISSUE TITLE
AppLiveUploadTask throws exception in AGP 7.3.1 and Gradle 7.5.1

### ISSUE THREAD

**Issue by nuhkoca** [browserstack/browserstack-gradle-plugin#61]
Hello,

I updated the plugin to 3.1.0 but now it started to throw an exception like below

```gradle
* What went wrong:
A problem was found with the configuration of task ':app:uploadInternalToBrowserstackAppLive' (type 'AppLiveUploadTask').
  - In plugin 'com.browserstack.gradle' type 'com.browserstack.gradle.AppLiveUploadTask' property 'command' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**Comment by bs-ashwanipathak** [comment]
This issue occurs due to version incompatibility. Please try downgrading gradle to <7. For ref.:https://stackoverflow.com/questions/67137816/flutter-project-fails-to-build-when-gradle-gets-upgraded-error-type-flutterta

There's a related issue here: https://github.com/flutter/flutter/issues/79155#issuecomment-812817965

**Comment by nuhkoca** [comment]
Sorry I can't downgrade Gradle version. The plugin should support newer Gradle versions I believe but thanks for the reply

**Comment by nuhkoca** [comment]
@bs-ashwanipathak can you please check my PR?
